In [28]:
import numpy as np
k=2

S = np.zeros((k, 0))

a = np.array([1,2])
b = np.array([2,3])
c = np.array([3,4])

S=np.hstack((S,np.matrix(a).T))
S=np.hstack((S,np.matrix(b).T))
S=np.hstack((S,np.matrix(c).T))
#S=np.hstack((S,b.T))
S

matrix([[1., 2., 3.],
        [2., 3., 4.]])

In [29]:
S[:,0]

matrix([[1.],
        [2.]])

In [30]:
S[:,0].dot(S[:,0].T)

matrix([[1., 2.],
        [2., 4.]])

In [35]:
D=np.matrix('1 0;0 1')
D

matrix([[1, 0],
        [0, 1]])

In [36]:
np.kron(S[:,0].dot(S[:,0].T), D)

matrix([[1., 0., 2., 0.],
        [0., 1., 0., 2.],
        [2., 0., 4., 0.],
        [0., 2., 0., 4.]])

In [10]:
a.dot(b)

5